Repository django/djangoproject.com, pull requests merged in 2022-12, with the labels that each got.

#1236 Updated search box shortcut and made it visible
  djangoproject/static/js/mod/search-key.js
Labels: accessibility, docs, search

#1290 Fixed #1289 -- Remove unnecessary step from README
  README.rst
Labels: docs, non-code-contribution

#1288 Fixed #1282 -- Migration to new Transifex CLI
  .tx/config
  README.rst
  requirements/dev.txt
Labels: release blocker, bug, i18n, dependencies, python

#1292 Fixed #1291 -- Standardize the CLI's instructions
  Makefile
  README.rst
Labels: docs, non-code-contribution

#1294 Fixed #1293 -- Modernize to Django 3.2/Python 3.8
  .pre-commit-config.yaml
  accounts/views.py
  aggregator/admin.py
  aggregator/management/commands/update_subscriptions.py
  aggregator/models.py
  blog/admin.py
  contact/forms.py
  dashboard/models.py
  dashboard/views.py
  djangoproject/middleware.py
  djangoproject/settings/common.py
  docs/management/commands/purge_docs_cache.py
  docs/management/commands/update_docs.py
  docs/models.py
  docs/tests.py
  foundation/admin.py
  foundation/models.py
  fundraising/forms.py
  fundraising/management/commands/create_stripe_plans.py
  fundraising/models.py
  fundraising/tests/test_models.py
  fundraising/tests/test_views.py
  members/models.py
  releases/admin.py
  tracdb/models.py
Labels: dependencies, python

#1296 Fixed #1295 -- Upgrade Dockerfile
  Dockerfile
  requirements/tests.txt
Labels: dependencies, non-code-contribution
