Repository django/djangoproject.com, pull requests merged in 2022-10, with the labels that each got.

#1226 Fixed #1225 -- Increase stale bot days
  .github/stale.yml
Labels: trac

#1230 Fix image release on change os preference
  djangoproject/static/js/mod/switch-dark-mode.js
Labels: styles, accessibility, bug

#1235 Clean Readme
  README.rst
Labels: in progress, docs, bug

#1029 Improve language/version switcher
  djangoproject/scss/_style.scss
  djangoproject/static/js/main.js
  djangoproject/static/js/mod/doc-switcher.js
  djangoproject/static/js/mod/version-switcher.js
  docs/templates/docs/doc.html
Labels: in progress, accessibility, docs

#1232 Refs #1003: Used system font stack for sans-serif text.
  djangoproject/scss/_utils.scss
  djangoproject/templates/base.html
  djangoproject/templates/styleguide.html
Labels: in progress, styles, accessibility

#1231 Fixed #952 -- Added wallpaper designs in higher resolution
  djangoproject/static/img/desktops/djangodesktop-1920x1080.png
  djangoproject/static/img/desktops/djangodesktop-3840x2160.png
  djangoproject/static/img/desktops/djangodesktop-7680x4320.png
  djangoproject/static/img/desktops/djangodesktop-thumbnail.png
  djangoproject/static/img/desktops/djangodesktop.svg
Labels: in progress, good first issue

#1243 Fixed #1242 -- Revert the usage of system font stack for sans-serif text
  djangoproject/scss/_utils.scss
  djangoproject/templates/base.html
  djangoproject/templates/styleguide.html
Labels: in progress, release blocker, accessibility, bug

#1256 Add a link to setting up a virtual python env
  README.rst
Labels: docs

#1262 Fix N+1 Query on Django Community page
  aggregator/urls.py
  aggregator/views.py
  djangoproject/templates/aggregator/index.html
Labels: in progress, bug
