Repository django/djangoproject.com, pull requests merged in 2024-11, with the labels that each got.

#1694 Updated Sphinx and related dependencies.
  requirements/common.txt
Labels: docs, dependencies

#1709 Update coverage
  requirements/tests.txt
Labels: dependencies

#1708 Update pre-commit
  .pre-commit-config.yaml
  requirements/dev.txt
Labels: dependencies

#1713 Updated to watchdog 6.0.0
  requirements/dev.txt
Labels: styles, dependencies

#1715 Update to pysocpg 3.2.3
  requirements/common.txt
Labels: dependencies, python

#1712 Update Django 5.0
  .pre-commit-config.yaml
  blog/models.py
  djangoproject/settings/common.py
  members/test_admin.py
  requirements/common.txt
Labels: bug, dependencies, python, help-needed

#1779 Remove Modernizr integration
  djangoproject/scss/_style.scss
  djangoproject/static/img/logo-andrevv.png
  djangoproject/static/img/logo-disqus.png
  djangoproject/static/img/logo-django.png
  djangoproject/static/img/logo-knight.png
  djangoproject/static/img/logo-mozilla.png
  djangoproject/static/img/logo-threespot.png
  djangoproject/static/js/lib/modernizr.js
  djangoproject/templates/base.html
Labels: styles, dependencies
