Repository django/djangoproject.com, pull requests merged in 2024-10, with the labels that each got.

#1627 Added production docker image with preview domain support
  .github/workflows/docker-publish.yml
  .github/workflows/docker-test-build.yml
  .github/workflows/tests.yml
  .gitignore
  Dockerfile
  djangoproject/settings/prod.py
  docker-compose.yml
  docker-entrypoint.dev.sh
  docker-entrypoint.prod.sh
  docker-entrypoint.sh
  requirements/prod.txt
Labels: ops

#1679 Add community section to the homepage
  djangoproject/templates/homepage.html
Labels: content, ux

#1678 Add support for markdown blog posts
  blog/admin.py
  blog/migrations/0003_entry_content_format_markdown.py
  blog/models.py
  blog/tests.py
  requirements/common.txt
Labels: blog, content

#1674 feat: Translation preparation for foundation app
  djangoproject/templates/foundation/coreawardcohort_list.html
  djangoproject/templates/foundation/meeting_archive.html
  djangoproject/templates/foundation/meeting_archive_day.html
  djangoproject/templates/foundation/meeting_archive_month.html
  djangoproject/templates/foundation/meeting_archive_year.html
  djangoproject/templates/foundation/meeting_detail.html
  foundation/admin.py
  foundation/feeds.py
  foundation/models.py
Labels: on hold
